Reapply policies app 19035
apperian/EASEJenkinsPlugin pull request #7
Opened 2018-10-08 07:48 UTC by purigarcia

2018-10-08 08:15 UTC, purigarcia commented on src/test/resources/com/apperian/api/test-configuration.properties.sample
> +APPERIAN_API_URL=https://afinley-centos7-ws.dev.apperian.com
Maybe we should remove this, as it is a public repo.

2018-10-08 08:23 UTC, jrodgut-sg requested changes

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +import com.apperian.api.applications.*;
do not import everything, just what you need

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +                        ex.getErrorDetails());
I think you have to return false, so the job fails

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +    private boolean policiesAreApplied(Application application) {
maybe a better name for the method is "arePoliciesApplied", as in this way it suggests that it returns a boolean

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +                    applyPolicies(apperianApi, appliedPolicies);
wrong indentation

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +                    ex.getErrorDetails());
You need to return false when an error happens

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/PublishFileCallable.java
> +                fail("Error wrapping the application, ended with wrap status: " + wrapStatus);
I think you need to raise some kind of exception so the exception is caught where this function is called and the job marked as failed.

2018-10-08 08:23 UTC, jrodgut-sg commented on src/test/resources/com/apperian/api/test-configuration.properties.sample
> +APPERIAN_API_URL=https://afinley-centos7-ws.dev.apperian.com
this file should not be filled with the configuration details, it is public

2018-10-08 08:23 UTC, jrodgut-sg commented on src/main/java/org/jenkinsci/plugins/ease/EaseUpload.java
> +    public boolean getReapplyPolicies() { return reapplyPolicies; }
Methods returning booleans usually start with "is" instead of "get", so probably "isReapplyPolicies" would be a better name which suggests that it returns a boolean.

2018-10-08 13:12 UTC, fin7710 commented on src/test/resources/com/apperian/api/test-configuration.properties.sample
> +APPERIAN_API_URL=https://afinley-centos7-ws.dev.apperian.com
This was committed by mistake, I've removed the changes.

2018-10-10 07:44 UTC, jrodgut-sg approved these changes

2018-10-10 07:45 UTC, merged